apiVersion: apps/v1
kind: Deployment  
metadata:
  name: frontend-app
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: piyu5233/frontend:latest
        ports:
        - name: tomcat
          containerPort: 8080
          protocol: TCP 